obj-m += mc24lc64t.o
obj-m += midstone_driver.o
midstone_driver-y := midstone.o \
          cpld_driver.o \
          cpld_b.o \
          cpld_1.o  \
          cpld_2.o \
          cpld_3.o \
          cpld_4.o \
          panel_led.o \
          pcie_fpga.o \
          midstone100th2_i2c_mapping.o \
          sff_led_test.o \
          timing_module.o
